### ISSUE TITLE
pytests failing

### ISSUE THREAD

**Issue by birkealine** [MisterXY89/konstanz-open-data-api#18]
~~import of our package files is not working~~
~~--> need to adapt the relative paths through which they are imported~~
module not found errors have been solved

**Comment by birkealine** [comment]
Is it a problem for the github server to download something in a pytest?

**Comment by birkealine** [comment]
Run pytest --rootdir=$HOME --pyargs opencity
============================= test session starts ==============================
platform linux -- Python 3.7.11, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /home/runner
collected 61 items

../../../tests/test_dataset_url_fetcher.py ........                      [ 13%]
../../../tests/test_functional.py .                                      [ 14%]
../../../tests/test_get_data.py ...                                      [ 19%]
../../../tests/test_save_data.py ......                                  [ 29%]
../../../tests/test_show_data.py ..........                              [ 45%]
../../../tests/test_API_helper/test_fetch_helper.py ............         [ 65%]
../../../tests/test_API_helper/test_id_helper.py ...                     [ 70%]
../../../tests/test_API_helper/test_show_data_helper.py ...F             [ 77%]
../../../tests/test_fetcher/test_basic_fetcher.py .....                  [ 85%]
../../../tests/test_fetcher/test_csv_fetcher.py ...                      [ 90%]
../../../tests/test_fetcher/test_json_fetcher.py ..                      [ 93%]
../../../tests/test_fetcher/test_kml_fetcher.py ..                       [ 96%]
../../../tests/test_fetcher/test_shp_fetcher.py ..                       [100%]

=================================== FAILURES ===================================
__________________________________ test_meta ___________________________________

show_data_helper = <opencity.API_helper.ShowDataHelper object at 0x7f510952d710>
current_list =                                       id  ...                                name
0   02d3de3e-417a-446d-8d34-6e6bdb89...     einwohner
58  75395570-1de4-4227-ad43-ecdc2cf0e74d  ...                       kfz_statistik

[59 rows x 9 columns]

    def test_meta(show_data_helper, current_list):
>       show_data_helper.meta(current_list, destroy_=True)

/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/opencity/tests/test_API_helper/test_show_data_helper.py:48: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/opencity/API_helper.py:268: in meta
    app = tk.Tk()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <tkinter.Tk object .>, screenName = None, baseName = 'pytest'
className = 'Tk', useTk = 1, sync = 0, use = None

    def __init__(self, screenName=None, baseName=None, className='Tk',
                 useTk=1, sync=0, use=None):
        """Return a new Toplevel widget on screen SCREENNAME. A new Tcl interpreter will
        be created. BASENAME will be used for the identification of the profile file (see
        readprofile).
        It is constructed from sys.argv[0] without extensions if None is given. CLASSNAME
        is the name of the widget class."""
        self.master = None
        self.children = {}
        self._tkloaded = 0
        # to avoid recursions in the getattr code in case of failure, we
        # ensure that self.tk is always _something_.
        self.tk = None
        if baseName is None:
            import os
            baseName = os.path.basename(sys.argv[0])
            baseName, ext = os.path.splitext(baseName)
            if ext not in ('.py', '.pyc'):
                baseName = baseName + ext
        interactive = 0
>       self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
E       _tkinter.TclError: no display name and no $DISPLAY environment variable

/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/tkinter/__init__.py:2023: TclError
---------------------------- Captured stdout setup -----------------------------
There is no file with name CURRENT_PACKAGE_LIST.csv in the directory: 
type object 'Config' has no attribute 'CURRENT_PACKAGE_LIST_FILE'
There is no file with name CURRENT_PACKAGE_LIST.csv in the directory: 
type object 'Config' has no attribute 'CURRENT_PACKAGE_LIST_FILE'
---------------------------- Captured stderr setup -----------------------------

  0%|          | 0/59 [00:00<?, ?it/s]
100%|██████████| 59/59 [00:00<00:00, 336228.17it/s]

  0%|          | 0/59 [00:00<?, ?it/s]
100%|██████████| 59/59 [00:00<00:00, 333959.43it/s]
=========================== short test summary info ============================
FAILED ../../../tests/test_API_helper/test_show_data_helper.py::test_meta - _...
=================== 1 failed, 60 passed in 96.74s (0:01:36) ====================
Error: Process completed with exit code 1.

**Comment by MisterXY89** [comment]
the error message "E       _tkinter.TclError: no display name and no $DISPLAY environment variable" indicates that the test may tries to display a tkinter GUI which is not possible and therfore the error is thrown.

Depending on how the test are executed/what config can be passed you might be able to add a display in the command line:
$  DISPLAY=:0 <<COMMAND>>
