### ISSUE TITLE
Show_data does not work for certain OS

### ISSUE THREAD

**Issue by Rahkakavee** [MisterXY89/konstanz-open-data-api#22]
show_data() does not work for mac if the parameter meta = True is set. Output: nan.

**Comment by SilkeHusse** [comment]
Same if the parameter overview = True is set.

**Comment by SilkeHusse** [comment]
Problem does not exist if CURRENT_PACKAGE_LIST file exists.

**Comment by SilkeHusse** [comment]
fixed code
